module.exports =  {
  /**
   * Get field tuple.
   * @returns {Object} fields and fieldNames.
   */
  getReportCsvFields: function () {

    let fields = [
      'project_id',
      'report_id',
      'target_location_reference_id',
      'cluster',
      'organization',
      'username',
      'email',
      'project_hrp_code',
      'project_title',
      'project_code',
      'donors',
      'programme_partners',
      'implementing_partners',
      'admin0name',
      'admin1pcode',
      'admin1name',
      'admin2pcode',
      'admin2name',
      'admin3pcode',
      'admin3name',
      'site_implementation_name',
      'site_type_name',
      'site_name',
      'report_month',
      'report_year',
      'activity_type_name',
      'activity_description_name',
      'activity_detail_name',
      'indicator_name',
      'category_type_name',
      'beneficiary_type_name',
      'beneficiary_category_name',
      'hrp_beneficiary_type_name',
      'strategic_objective_name',
      'strategic_objective_description',
      'sector_objective_name',
      'sector_objective_description',
      'delivery_type_name',
      'units',
      'unit_type_name',
      'transfer_type_value',
      'mpc_delivery_type_name',
      'mpc_mechanism_type_name',
      'mpc_package_type_name',
      'transfer_category_name',
      'grant_type_name',
      'total_amount',
      'households',
      'families',
      'boys',
      'girls',
      'men',
      'women',
      'elderly_men',
      'elderly_women',
      'total_beneficiaries',
      'createdAt',
      'updatedAt'
    ],
    fieldNames = [
      'Project ID',
      'Report ID',
      'Target Location ID',
      'Cluster',
      'Organization',
      'Focal Point',
      'Email',
      'HRP Code',
      'Project Title',
      'Project Code',
      'Project Donors',
      'Programme Partners',
      'Implementing Partners',
      'Country',
      'Admin1 Pcode',
      'Admin1 Name',
      'Admin2 Pcode',
      'Admin2 Name',
      'Admin3 Pcode',
      'Admin3 Name',
      'Site Implementation',
      'Site Type',
      'Location Name',
      'Report Month',
      'Report Year',
      'Activity Type',
      'Activity Description',
      'Activity Details',
      'Indicator',
      'Category Type',
      'Beneficiary Type',
      'Beneficiary Category',
      'HRP Beneficiary Type',
      'Strategic Objective',
      'Strategic Objective Description',
      'Sector Objective',
      'Sector Objective Description',
      'Population',
      'Amount',
      'Unit Type',
      'Cash Transfers',
      'Cash Delivery Type',
      'Cash Mechanism Type',
      'Package Type',
      'Transfer Category',
      'Grant Type',
      'Total Transferred',
      'Households',
      'Families',
      'Boys',
      'Girls',
      'Men',
      'Women',
      'Elderly Men',
      'Elderly Women',
      'Total',
      'Created',
      'Last Update'
    ];

      return { fields, fieldNames };
  }
};
